name: "Twilio guMCP Server"
icon: "assets/icon.png"
description: "Interact with Twilio's messaging, voice, verification, and communication APIs"
documentation_path: "README.md"
tools:
  # Messaging Tools
  - name: "send_message"
    description: "Send SMS, MMS, or WhatsApp messages"
  - name: "list_messages"
    description: "List message history"
  - name: "fetch_message"
    description: "Fetch a message by SID"
  - name: "delete_message"
    description: "Delete a message by SID"
  # Voice Tools
  - name: "make_call"
    description: "Make an outbound voice call with TwiML or text-to-speech"
  - name: "list_calls"
    description: "List recent calls"
  - name: "fetch_call"
    description: "Fetch a call by SID"
  # Verify Tools
  - name: "list_verify_services"
    description: "List all Twilio Verify services"
  - name: "create_verify_service"
    description: "Create a new Twilio Verify service"
  - name: "start_verification"
    description: "Send a verification code via SMS, call, etc."
  - name: "check_verification"
    description: "Check a verification code"
  # Lookup Tools
  - name: "lookup_phone_number"
    description: "Lookup phone number information and carrier data"
  # Conversations Tools
  - name: "list_conversation_services"
    description: "List all conversation services"
  - name: "create_conversation_service"
    description: "Create a new conversation service"
  - name: "list_conversations"
    description: "List conversations in a service"
  - name: "create_conversation"
    description: "Create a new conversation"
  - name: "add_conversation_participant"
    description: "Add a participant to a conversation"
  - name: "send_conversation_message"
    description: "Send a message in a conversation"
  # Video Tools
  - name: "list_video_rooms"
    description: "List all video rooms"
  - name: "create_video_room"
    description: "Create a new video room"
  - name: "fetch_video_room"
    description: "Fetch details about a video room"
  - name: "complete_video_room"
    description: "Complete (end) a video room" 