name: "ClickUp guMCP Server"
icon: "assets/icon.png"
description: "Interact with ClickUp task management and project tracking"
documentation_path: "README.md"
resources:
  - name: "workspaces"
    description: "ClickUp workspaces/teams that the user has access to"
  - name: "spaces"
    description: "Project spaces organized within workspaces"
tools:
  - name: "get_authenticated_user"
    description: "Get information about the authenticated user"
  - name: "get_workspaces"
    description: "Get all workspaces/teams the user has access to"
  - name: "get_spaces"
    description: "Get all spaces in a workspace"
  - name: "get_folders"
    description: "Get all folders in a space"
  - name: "get_lists"
    description: "Get all lists in a folder or space"
  - name: "get_tasks"
    description: "Get tasks from a list"
  - name: "get_task_by_id"
    description: "Get a specific task by ID"
  - name: "create_task"
    description: "Create a new task in a list"
  - name: "update_task"
    description: "Update an existing task"
  - name: "add_comment"
    description: "Add a comment to a task"
  - name: "create_list"
    description: "Create a new list in a folder or space"
  - name: "create_folder"
    description: "Create a new folder in a space"
